# Generated by Django 2.2.24 on 2021-10-10 05:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Branch',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('branch_name', models.CharField(max_length=128)),
                ('address', models.TextField(blank=True, null=True)),
                ('branch_phone', models.CharField(blank=True, max_length=16, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('department_name', models.CharField(max_length=128)),
                ('department_desc', models.TextField()),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='department.Branch')),
            ],
        ),
    ]
